server.port=8080
server.servlet.context-path=/api/v1

# Perfil padrao SQLite (100% offline e embarcado)
spring.datasource.url=jdbc:sqlite:../penas_alternativas.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Servico Biometrico Facial (Microservico Python FastAPI em loopback)
cpma.facial.service.url=http://127.0.0.1:8001

# Seguranca e Tokens
cpma.security.jwt.secret=CPMA_SECRET_KEY_FOR_LOCAL_NETWORK_AUTHENTICATION_AND_TOTEM_TERMINAL_2026
cpma.security.jwt.expiration-hours=24

# Respostas JSON
spring.jackson.deserialization.fail-on-unknown-properties=false
